name: Build Android
on: [workflow_call]
jobs:
  build-android:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          cache: gradle
      - name: build
        run: ./gradlew assembleDebug assembleRelease --info --parallel
      - uses: actions/upload-artifact@v4
        with:
          name: testapp-apk
          path: testapp/build/outputs/apk/
          if-no-files-found: error
      - uses: actions/upload-artifact@v4
        with:
          name: vpnmanager-aars
          path: vpnmanager/build/outputs/aar/
          if-no-files-found: error
